### PR TITLE
refactor!: rewrite and restructure existing functionality

### PR DESCRIPTION
**Pull request by jose-elias-alvarez**
This PR tracks progress on #11. At the moment, this branch recreates the plugin's existing functionality but removes the following options: 

- `modifier`: not useful, since anything but `:t` is massive, and modifying it messes with the plugin's automatic ambiguity resolution
- `index_format`, `padding`, and `icons`: removed in favor of `tab_format` (see the README)
- `kill_maps`, `custom_command`, and `custom_map_prefix`: removed in favor of `buftabline.map()` (see the README)
- `show_no_name_buffers`: not useful
- `next_indicator`: always set to `>`, which matches the automatic (and non-customizable) left-side truncation marker

Other changes:
- Icon colors are enabled by default, which is consistent with other plugins (e.g. Telescope)
- `hlgroups` is now a table, but I've put in backwards compatibility for `hlgroup_current` and `hlgroup_normal`

`tab_format` takes care of #10, #12, #13, and #14. This leaves the following tasks:

- [x] Support customizable flag markers (trivial)
- [x] Support more highlight groups (not too bad)
- [ ] Fix broken tests, i.e. all of them (this is a pain, and I plan on focusing on integration tests that assert against the tabline itself)
- [x] Consider padding (not hard to implement in the way [barbar](https://github.com/romgrk/barbar.nvim#integration-with-filetree-plugins) does it, but it makes tabline generation stateful, so I have to weigh the advantages)

### CODE REVIEW

**Comment by mroavi** [comment]
Hi Jose. I noticed a small issue. I set the `modified` option inside the `flags` option to an empty string. I also added a `|` separator to the `tab_format` option:
```lua
local options = {
	tab_format = " #{n}: #{b}#{f} |",
	flags = {
		modified = "",
		not_modifiable = "[-]",
		readonly = "[RO]",
	},
}
``` 
I was hoping to see no effect after making a change to the current buffer. However, an empty space does appear:

No change:
image

Buffer changed:
image

Do you agree that this is a problem?

**Comment by mroavi** [comment]
Ohh I just realized that by commenting out the whole line, I get the behavior I wanted. However, I do think that setting `modified = ""` should result in the same behavior.

**Comment by jose-elias-alvarez** [comment]
Yep, agreed. Just pushed a commit that should take care of it. Let me know if you have any more feedback for now – I'll work on the highlight groups next time I have a chance.

**Comment by jose-elias-alvarez** [comment]
I've implemented highlight groups (a breaking change to existing config keys) and made the decision not to include padding, mostly because I don't think I'd be able to do it justice, since I don't use any file tree plugins myself.

I'll rewrite the tests for peace of mind before merging, but other than that I think this is (hopefully) good to go.

**Comment by mroavi** [comment]
Hi Jose, I just tested the new highlight groups but they don't seem to work for me. On the other hand, the old approach of using `hlgroup_current` and `hlgroup_normal` (instead of `hlgroups`) does function as expected. I pulled your last two commits of the develop branch.

**Comment by mroavi** [comment]
By the way, I also noticed that the `modified` option inside the `flags` table is also not working: No matter what I set it to, `[+]` is always displayed.

**Comment by jose-elias-alvarez** [comment]
Whoops! I was testing this out by directly modifying the plugin's options, but the timing of getting the user's flags and highlight groups wasn't working. Thanks for describing the problem clearly so I could diagnose it. Could you let me know if it works for you on the latest commit?

**Comment by mroavi** [comment]
Everything seems to be working fine now! Thanks for spending time on this.

**Comment by jose-elias-alvarez** [comment]
Thanks for confirming! I just finished rewriting the tests, so I'm going to merge this.

**Pull request merged**
